name: cronjob
on:
    schedule:
      - cron: '* * * * *'

jobs: 
  cron:
    runs-on: ubntu- latest

    steps: 
    - name: clone reps
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'

    - name: Run python script
      run: python 01.hello.py




