name: Run hello-world from py script
on: push


jobs:
    Hello:
        runs-on: ubuntu-latest

        steps:
        - name: Clone repo
          uses: actions/checkout@v3


        - name: Setup python
          uses: actions/setup-python@v5
          with:
           python-version: '3.13'

        - name: run a py script
          run:  python 01.helllo.py