 name: Send mail
 on : push

 jobs:
    mail:
        runs-on: ubuntu-latest

        steps:
         - name: Print hellow world
           run: echo "hellow world"

         - name: Send email
           if: ${{ always() }}
           uses: dawidd6/action-send-mail@v3.6.0
           with:
                 server_address: smtp.google.com
                 server_port: 465
                 password: ${{secrets.MAIL_PASSWORD}}
                 username: ${{secrets.MAIL_ADDRESS}}
                 to: veilb4u@gmail.com
                 subject: test veil
                 body: testing action mail

