 name: Send mail
 on : push

 jobs:
    mail:
        runs-on: ubuntu-latest

        steps:
         - name: Print hellow world
           run: echo "hellow world"

         - name: Send email
           if: ${{ always() }}
           uses: dawidd6/action-send-mail@v3.6.0
           with:
                 host: smtp.google.com
                 port: 465
                 password: ${{secrets.MAIL_PASSWORD}}
                 from: ${{secrets.MAIL_ADDRESS}}
                 to: veilb4u@gmail.com
                 subject: test veil mail
                 body: testing action mail.
                 contentType: text/plain
                 attachments: '[{"path":"README.md"}]'

